export type Locale = "ar" | "en";
export type Bilingual = { ar: string; en: string };

export const siteConfig = {
  name: { ar: "سعرلي", en: "Saarly" },
  tagline: { ar: "صوّر، قارن، وفّر", en: "Capture, compare, save" },
  siteUrl: process.env.NEXT_PUBLIC_SITE_URL || "https://saarly.app",
  supportEmail: process.env.NEXT_PUBLIC_SUPPORT_EMAIL || "info@saarly.app",
  supportPhone: process.env.NEXT_PUBLIC_SUPPORT_PHONE || "",
  appStoreUrl: process.env.NEXT_PUBLIC_APP_STORE_URL || "",
  googlePlayUrl: process.env.NEXT_PUBLIC_GOOGLE_PLAY_URL || "",
  portalUrl: process.env.NEXT_PUBLIC_MERCHANT_PORTAL_URL || "/merchant-login",
  social: {
    facebook: process.env.NEXT_PUBLIC_FACEBOOK_URL || "",
    instagram: process.env.NEXT_PUBLIC_INSTAGRAM_URL || "",
    linkedin: process.env.NEXT_PUBLIC_LINKEDIN_URL || "",
  },
} as const;

export const navItems: Array<{ href: string; label: Bilingual }> = [
  { href: "/#how-it-works", label: { ar: "كيف يعمل", en: "How it works" } },
  { href: "/#merchants", label: { ar: "للمتاجر", en: "For stores" } },
  { href: "/#faq", label: { ar: "الأسئلة الشائعة", en: "FAQ" } },
  { href: "/support", label: { ar: "الدعم", en: "Support" } },
];

export const buyerFeatures: Array<{ icon: string; title: Bilingual; body: Bilingual }> = [
  { icon: "list", title: { ar: "طلب واحد لاحتياجات متعددة", en: "One request, many items" }, body: { ar: "اجمع المنتجات المطلوبة في قائمة واحدة بدل السؤال في أكثر من مكان.", en: "Collect all required products in one list instead of asking several stores separately." } },
  { icon: "store", title: { ar: "عروض من متاجر مناسبة", en: "Offers from relevant stores" }, body: { ar: "يرسل النظام الطلب إلى المتاجر المناسبة حسب الأقسام والموقع وفق البيانات المتاحة.", en: "The request reaches relevant stores based on category and location data." } },
  { icon: "compare", title: { ar: "مقارنة واضحة", en: "Clear comparison" }, body: { ar: "راجع أسعار البنود والتوفر والتفاصيل قبل اختيار العرض المناسب.", en: "Review item prices, availability, and details before choosing an offer." } },
  { icon: "target", title: { ar: "طلب مخصوص", en: "Direct store request" }, body: { ar: "أرسل طلب تسعير إلى متجر معين عندما تعرف المتجر الذي تريد التعامل معه.", en: "Send a quote request to one selected store when you already know where to ask." } },
  { icon: "history", title: { ar: "متابعة الطلبات", en: "Request history" }, body: { ar: "تابع الطلبات والعروض السابقة وحالاتها من مكان واحد.", en: "Track previous requests, offers, and their current states in one place." } },
  { icon: "bell", title: { ar: "تنبيهات الأسعار", en: "Price alerts" }, body: { ar: "تابع المنتجات واحصل على تنبيه عند تغير السعر وفق شروط التنبيه المفعلة.", en: "Watch products and receive alerts when enabled price conditions change." } },
];

export const merchantFeatures: Array<{ icon: string; title: Bilingual; body: Bilingual }> = [
  { icon: "store", title: { ar: "متجر وفروع", en: "Store and branches" }, body: { ar: "إدارة بيانات المتجر والفروع ومراجعة حالات الاعتماد.", en: "Manage store and branch data and review approval states." } },
  { icon: "box", title: { ar: "منتجات وأسعار", en: "Products and prices" }, body: { ar: "إضافة المنتجات وتحديث الأسعار والكميات والتوفر.", en: "Add products and update prices, quantities, and availability." } },
  { icon: "quote", title: { ar: "طلبات عامة ومخصوصة", en: "General and direct requests" }, body: { ar: "استقبال طلبات التسعير والرد على كل بند حسب طريقة تشغيل المتجر.", en: "Receive quote requests and price each item according to the store mode." } },
  { icon: "users", title: { ar: "إدارة الموظفين", en: "Staff management" }, body: { ar: "إضافة أعضاء المتجر وتحديد الفروع والصلاحيات المتاحة لهم.", en: "Add store members and assign branch scopes and permissions." } },
  { icon: "desktop", title: { ar: "التطبيق والكمبيوتر", en: "Mobile and desktop" }, body: { ar: "استخدم نفس حساب المتجر في التطبيق وبوابة الويب.", en: "Use the same store account in the app and web portal." } },
  { icon: "receipt", title: { ar: "الحساب والمدفوعات", en: "Account and billing" }, body: { ar: "تابع الفترة المجانية والاشتراك والعمولة وطلبات الدفع من بوابة المتاجر.", en: "Follow trial, subscription, commission, and payment requests in the merchant portal." } },
];

export const howSteps: Array<{ number: string; icon: string; title: Bilingual; body: Bilingual }> = [
  { number: "01", icon: "upload", title: { ar: "أرسل طلبك", en: "Send your request" }, body: { ar: "ارفع صورة أو ملفًا، أو اكتب البنود يدويًا.", en: "Upload an image or file, or enter the items manually." } },
  { number: "02", icon: "check", title: { ar: "راجع البنود", en: "Review the items" }, body: { ar: "تأكد من الأسماء والكميات قبل الإرسال.", en: "Confirm names and quantities before submission." } },
  { number: "03", icon: "compare", title: { ar: "قارن الردود", en: "Compare responses" }, body: { ar: "راجع الأسعار والتوفر وتفاصيل كل عرض.", en: "Review prices, availability, and offer details." } },
  { number: "04", icon: "target", title: { ar: "اختر الأنسب", en: "Choose what fits" }, body: { ar: "اقبل العرض المناسب لك وتابع الطلب.", en: "Accept the suitable offer and follow the order." } },
];

export const faqs: Array<{ question: Bilingual; answer: Bilingual }> = [
  { question: { ar: "ما هو سعرلي؟", en: "What is Saarly?" }, answer: { ar: "سعرلي منصة تساعد المشتري على إرسال قائمة احتياجات والحصول على عروض أسعار من متاجر مناسبة، كما توفر للتاجر أدوات لإدارة المنتجات وطلبات التسعير.", en: "Saarly helps buyers send a list of needs and receive quotes from relevant stores, while giving stores tools to manage products and quote requests." } },
  { question: { ar: "كيف أرسل طلبًا؟", en: "How do I send a request?" }, answer: { ar: "من التطبيق يمكنك رفع صورة أو ملف أو إدخال البنود يدويًا، ثم مراجعة القائمة قبل الإرسال.", en: "In the app, upload an image or file or enter items manually, then review the list before sending." } },
  { question: { ar: "هل استخدام التطبيق للمشتري مجاني؟", en: "Is the buyer app free?" }, answer: { ar: "لا يعرض النظام الحالي رسومًا على استخدام المشتري للتطبيق. أي تغيير مستقبلي يظهر بوضوح داخل التطبيق والسياسات قبل تطبيقه.", en: "The current system does not show a buyer usage fee. Any future change will be disclosed in the app and policies before it applies." } },
  { question: { ar: "كيف تصلني عروض الأسعار؟", en: "How do quotes reach me?" }, answer: { ar: "يرسل الطلب العام إلى المتاجر المناسبة، وقد تصل بعض العروض فورًا من الكتالوج وبعضها لاحقًا بعد التسعير اليدوي.", en: "General requests reach relevant stores. Some catalog offers may arrive immediately, while manually priced offers may arrive later." } },
  { question: { ar: "هل يمكنني الطلب من متجر معين؟", en: "Can I ask one specific store?" }, answer: { ar: "نعم، يمكنك فتح صفحة متجر وإرسال طلب مخصوص يصل إليه وحده عندما يكون المتجر قادرًا على استقبال الطلبات.", en: "Yes. Open a store page and send a direct request that reaches only that store when it can receive requests." } },
  { question: { ar: "كيف يسجل صاحب المتجر؟", en: "How does a store register?" }, answer: { ar: "تقدر تسجل المتجر من تطبيق سعرلي أو من الموقع. بعد إرسال البيانات والمستندات، الإدارة تراجع الطلب وتبلغك بالقبول أو سبب الرفض، وبعد الاعتماد تستخدم نفس البريد في بوابة المتاجر.", en: "Register from the Saarly app or website. Administration reviews the submitted details and documents, then sends the approval or rejection reason. After approval, use the same email in the merchant portal." } },
  { question: { ar: "هل الحساب نفسه يعمل على التطبيق والكمبيوتر؟", en: "Does the same account work on mobile and desktop?" }, answer: { ar: "نعم، بوابة المتاجر تستخدم الحساب نفسه والبيانات نفسها الموجودة في التطبيق.", en: "Yes. The merchant portal uses the same account and the same data as the app." } },
  { question: { ar: "كيف أتواصل مع الدعم؟", en: "How do I contact support?" }, answer: { ar: "استخدم نموذج الدعم في الموقع أو صفحة الدعم داخل التطبيق. عند تسجيل الدخول يرتبط الطلب بحسابك متى أمكن.", en: "Use the website support form or the in-app support page. When signed in, the request is linked to your account whenever possible." } },
  { question: { ar: "كيف أحذف حسابي؟", en: "How do I delete my account?" }, answer: { ar: "يمكنك طلب الحذف من إعدادات التطبيق أو صفحة حذف الحساب. قد تُجهّل أو يُحتفظ ببعض السجلات اللازمة للالتزامات القانونية أو المالية.", en: "Request deletion from app settings or the account deletion page. Some legally or financially required records may be anonymized or retained." } },
  { question: { ar: "كيف تتم حماية بياناتي؟", en: "How is my data protected?" }, answer: { ar: "تُستخدم صلاحيات على مستوى قاعدة البيانات والسيرفر، وتُحفظ مستندات التحقق وإثباتات الدفع في تخزين خاص، ولا تُعرض بيانات التواصل كدليل عام.", en: "Database and server authorization are used, verification documents and payment proofs are stored privately, and contact details are not exposed as a public directory." } },
];

type PolicySection = { title: Bilingual; body: Bilingual };
type Policy = { title: Bilingual; intro: Bilingual; updated: Bilingual; legalReview?: boolean; sections: PolicySection[] };

export const policyContent: Record<"privacy" | "terms" | "refund" | "deleteAccount", Policy> = {
  privacy: {
    title: { ar: "سياسة الخصوصية", en: "Privacy Policy" },
    updated: { ar: "آخر تحديث: 21 يوليو 2026", en: "Last updated: July 21, 2026" },
    intro: { ar: "نحن نحترم خصوصيتك ونلتزم بحماية بياناتك الشخصية. توضح هذه السياسة كيف نجمع معلوماتك ونستخدمها ونحميها عند استخدام سعرلي.", en: "We respect your privacy and are committed to protecting your personal data. This policy explains how we collect, use, and protect information when you use Saarly." },
    sections: [
      { title: { ar: "1. البيانات التي نقوم بجمعها", en: "1. Data we collect" }, body: { ar: "بيانات الحساب: الاسم ورقم الهاتف والبريد الإلكتروني عند التسجيل.\n\nبيانات الاستخدام: الطلبات وعمليات البحث والمنتجات المفضلة والتقييمات.\n\nبيانات الجهاز والموقع: نوع الجهاز ونظام التشغيل والموقع الجغرافي عند تفعيله لتحسين الخدمة وعرض متاجر وعروض قريبة.\n\nعند استخدام وظائف إضافية قد نعالج صور الفواتير والملفات والتسجيلات الصوتية والبنود المستخرجة منها. وبالنسبة للمتاجر قد نعالج بيانات المتجر والفروع والموظفين ومستندات التحقق وإثباتات الدفع.", en: "Account data: name, phone number, and email during registration.\n\nUsage data: requests, searches, favorite products, and reviews.\n\nDevice and location data: device type, operating system, and location when enabled to improve the service and show nearby stores and offers.\n\nWhen additional features are used, we may process invoice images, files, audio recordings, and extracted items. For merchants, this may include store, branch, staff, verification-document, and payment-proof data." } },
      { title: { ar: "2. كيف نستخدم بياناتك", en: "2. How we use your data" }, body: { ar: "نستخدم البيانات لتشغيل الخدمة وتحسينها، وتنفيذ الطلبات ومقارنة الأسعار وتوجيه الطلبات إلى متاجر مناسبة، ودعم العملاء، وإرسال تحديثات مهمة عن الطلبات والشحن والعروض المرتبطة بالحساب، ومراجعة المتاجر والمدفوعات، واكتشاف ومنع الاحتيال أو الاستخدام غير المصرح به.", en: "We use data to operate and improve the service, process requests, compare prices, route requests to relevant stores, provide support, send important request, shipping, and account-offer updates, review stores and payments, and detect or prevent fraud and unauthorized use." } },
      { title: { ar: "3. مشاركة البيانات ومقدمو الخدمة", en: "3. Data sharing and service providers" }, body: { ar: "لا نبيع أو نؤجر بياناتك الشخصية. قد نشارك البيانات اللازمة فقط مع مزودي الخدمة الذين يساعدون في تشغيل النظام أو إتمام الطلبات، مثل Supabase للمصادقة وقاعدة البيانات والتخزين، وOpenAI لمعالجة محتوى الصور والملفات عند تفعيل التحليل بالذكاء الاصطناعي، وTomTom لخدمات الموقع أو المسارات عند استخدامها، ومزودي البريد والإشعارات والشحن والدفع حسب الوظائف المفعلة.", en: "We do not sell or rent personal data. We may share only necessary data with service providers that help operate the system or complete requests, including Supabase for authentication, database, and storage, OpenAI for image and file processing when AI analysis is enabled, TomTom for location or routing where used, and email, notification, shipping, and payment providers according to enabled features." } },
      { title: { ar: "4. حماية بياناتك", en: "4. Data protection" }, body: { ar: "نتخذ إجراءات أمنية لحماية البيانات من الوصول أو التعديل أو الإفصاح غير المصرح به. تُستخدم صلاحيات على مستوى قاعدة البيانات والسيرفر، وتُحفظ المستندات الحساسة وإثباتات الدفع في تخزين خاص، وتظهر للمخولين عبر روابط مؤقتة عند الحاجة.", en: "We use security measures to protect data from unauthorized access, changes, or disclosure. Database and server authorization are applied, sensitive documents and payment proofs are stored privately, and authorized users receive temporary access links when needed." } },
      { title: { ar: "5. حقوقك والتحكم في الحساب", en: "5. Your rights and account controls" }, body: { ar: "يمكنك الوصول إلى بياناتك وتعديلها من الإعدادات، وطلب حذف حسابك وبياناتك، وإيقاف الإشعارات التسويقية مع استمرار الإشعارات المهمة اللازمة لتشغيل الطلبات والحساب. قد نحتاج إلى الاحتفاظ بسجلات محدودة أو تجهيلها عندما تكون مطلوبة للالتزامات القانونية أو المالية أو لمنع إساءة الاستخدام.", en: "You can access and edit your data in Settings, request account and data deletion, and disable marketing notifications while continuing to receive important operational notifications. Limited records may need to be retained or anonymized for legal, financial, or abuse-prevention obligations." } },
      { title: { ar: "6. ملفات تعريف الارتباط والتخزين المحلي", en: "6. Cookies and local storage" }, body: { ar: "يستخدم موقع الويب ملفات تعريف الارتباط أو التخزين المحلي لتذكر الجلسة واللغة والمظهر وتحسين تجربتك. لا تُخزن أسرار السيرفر أو بيانات البطاقات البنكية في المتصفح.", en: "The website uses cookies or local storage to remember the session, language, and appearance and improve the experience. Server secrets and bank-card data are not stored in the browser." } },
      { title: { ar: "7. التغييرات على السياسة", en: "7. Policy changes" }, body: { ar: "قد نحدّث هذه السياسة من وقت لآخر. يتم توضيح التغييرات الجوهرية داخل التطبيق أو الموقع قبل أو عند بدء سريانها.", en: "We may update this policy from time to time. Material changes are communicated in the app or website before or when they take effect." } },
      { title: { ar: "8. تواصل معنا", en: "8. Contact us" }, body: { ar: "لأي استفسار متعلق بالخصوصية، تواصل معنا عبر support@saarly.app أو نموذج الدعم في الموقع.", en: "For privacy questions, contact support@saarly.app or use the website support form." } },
    ],
  },
  terms: {
    title: { ar: "الشروط والأحكام", en: "Terms and Conditions" },
    updated: { ar: "آخر تحديث: 19 يوليو 2026", en: "Last updated: July 19, 2026" },
    intro: { ar: "باستخدامك لتطبيق أو موقع سعرلي فإنك توافق على الالتزام بالشروط والأحكام التالية.", en: "By using the Saarly app or website, you agree to the following terms and conditions." },
    sections: [
      { title: { ar: "1. طبيعة الخدمة", en: "1. Service nature" }, body: { ar: "سعرلي منصة لمقارنة الأسعار والعروض من متاجر مختلفة ووسيط تقني لتبادل طلبات التسعير والمعلومات. سعرلي لا يبيع المنتجات المادية مباشرة.", en: "Saarly is a platform for comparing prices and offers from different stores and a technical intermediary for quote requests and information. Saarly does not directly sell physical products." } },
      { title: { ar: "2. دقة الأسعار والعروض", en: "2. Price and offer accuracy" }, body: { ar: "الأسعار والعروض تعتمد على بيانات المتاجر ويتم تحديثها وفق استخدام المتجر للنظام. قد تتغير الأسعار أو حالة التوفر دون إشعار مسبق، لذلك لا نضمن دقة السعر بنسبة 100% وقت الشراء. صلاحية العرض وتوفر المنتج مسؤولية المتجر البائع، ويجب مراجعة السعر النهائي قبل إتمام الطلب.", en: "Prices and offers depend on store data and are updated according to store use of the system. Prices or availability may change without notice, so 100% accuracy at purchase time cannot be guaranteed. Offer validity and product availability are the seller's responsibility, and the final price should be reviewed before completing an order." } },
      { title: { ar: "3. الطلبات والتوصيل والمنتجات", en: "3. Orders, delivery, and products" }, body: { ar: "تتحمل المتاجر مسؤولية جودة المنتجات والتوفر والتسليم وسياسات الاستبدال والاسترجاع الخاصة بها وفق القانون. يوضح كل تدفق داخل النظام الطرف المسؤول. عند تفعيل الشراء المباشر يكون دفع المشتري ثمن المنتج للمتجر منفصلًا تمامًا عن اشتراك المتجر المدفوع إلى سعرلي.", en: "Stores are responsible for product quality, availability, delivery, and their replacement or return policies under applicable law. Each system flow identifies the responsible party. When direct purchase is enabled, the buyer's payment for physical products to the store is entirely separate from the merchant subscription paid to Saarly." } },
      { title: { ar: "4. حساب المستخدم", en: "4. User account" }, body: { ar: "أنت مسؤول عن الحفاظ على سرية بيانات دخولك وتقديم معلومات صحيحة ودقيقة. يحق لسعرلي إيقاف أي حساب يخالف الشروط أو يسيء استخدام الطلبات أو الرسائل أو المنصة.", en: "You are responsible for keeping login details confidential and providing correct and accurate information. Saarly may suspend accounts that violate these terms or misuse requests, messages, or the platform." } },
      { title: { ar: "5. المتاجر والفترة المجانية والمحاسبة", en: "5. Merchants, free trial, and billing" }, body: { ar: "يبدأ المتجر المؤهل بفترة مجانية بعد اعتماد المتجر وبدء نظام تحقيق الدخل وفق إعدادات النظام. بعد انتهاء الفترة المجانية يختار صاحب المتجر من بوابة المتاجر طريقة المحاسبة المتاحة: اشتراك مدفوع إلى سعرلي أو عمولة على العمليات المؤهلة، حسب الخيارات التي فعّلها الأدمن. قد تُطبق فترة سماح، وبعد انتهائها يمكن إيقاف استقبال الطلبات الجديدة حتى تسوية حالة الحساب.", en: "An eligible store begins a free period after approval and monetization activation according to system settings. After the free period, the owner chooses an available billing model in the merchant portal: a subscription paid to Saarly or commission on eligible transactions, depending on admin-enabled options. A grace period may apply, after which new requests can be suspended until the account is resolved." } },
      { title: { ar: "6. الملكية الفكرية", en: "6. Intellectual property" }, body: { ar: "جميع الحقوق المتعلقة بالتطبيق والموقع والشعار والتصميم والمحتوى مملوكة لسعرلي أو لأصحابها المرخصين، ولا يجوز استخدامها دون إذن مكتوب.", en: "All rights related to the app, website, logo, design, and content belong to Saarly or licensed owners and may not be used without written permission." } },
      { title: { ar: "7. تحديد المسؤولية", en: "7. Limitation of liability" }, body: { ar: "نبذل جهدًا معقولًا لتوفير خدمة دقيقة وآمنة، لكن سعرلي غير مسؤول عن أضرار ناتجة عن الاعتماد على معلومات متجر غير صحيحة أو عن نزاع تجاري يقع بين المشتري والمتجر خارج مسؤوليات سعرلي المباشرة، وذلك في حدود القانون.", en: "We make reasonable efforts to provide an accurate and secure service, but Saarly is not responsible for damage caused by inaccurate store information or commercial disputes between buyers and stores outside Saarly's direct responsibilities, to the extent permitted by law." } },
      { title: { ar: "8. تعديل الشروط والقانون المطبق", en: "8. Changes and governing law" }, body: { ar: "قد نعدل هذه الشروط عند الحاجة، ويعني استمرار الاستخدام بعد سريان التعديلات قبولها. تخضع هذه الشروط لقوانين جمهورية مصر العربية ما لم يفرض القانون المختص خلاف ذلك.", en: "We may update these terms when needed. Continued use after changes take effect means acceptance. These terms are governed by the laws of the Arab Republic of Egypt unless applicable law requires otherwise." } },
      { title: { ar: "9. تواصل معنا", en: "9. Contact us" }, body: { ar: "للاستفسارات المتعلقة بالشروط، تواصل معنا عبر support@saarly.app أو نموذج الدعم.", en: "For terms-related questions, contact support@saarly.app or use the support form." } },
    ],
  },
  refund: {
    title: { ar: "سياسة الاسترداد", en: "Refund Policy" },
    updated: { ar: "آخر تحديث: يوليو 2026", en: "Last updated: July 2026" },
    legalReview: true,
    intro: { ar: "توضح هذه السياسة الفرق بين استرداد مدفوعات اشتراك المتجر واسترداد قيمة منتج مادي تم شراؤه من متجر.", en: "This policy explains the difference between refunding a merchant subscription payment and refunding a physical product purchased from a store." },
    sections: [
      { title: { ar: "1. اشتراكات المتاجر", en: "1. Merchant subscriptions" }, body: { ar: "طلب استرداد اشتراك المتجر يُقدّم إلى دعم سعرلي ويُراجع حسب حالة التفعيل ومدة الاستخدام ووسيلة الدفع وأي التزامات أو مبالغ مستحقة على الحساب. لا يُعد إرسال الطلب موافقة تلقائية على الاسترداد.", en: "A merchant subscription refund request is submitted to Saarly Support and reviewed based on activation status, usage period, payment method, and any account obligations or outstanding amounts. Submission does not mean automatic approval." } },
      { title: { ar: "2. الدفع اليدوي", en: "2. Manual payments" }, body: { ar: "التحويلات اليدوية تحتاج مراجعة إثبات الدفع والتحقق من وصول المبلغ. عند الموافقة على الاسترداد يتم تحديد وسيلة ومدة التنفيذ بعد التحقق من بيانات صاحب الحساب، ولا يُعاد المبلغ إلى حساب مختلف دون تحقق إضافي.", en: "Manual transfers require payment-proof review and confirmation that funds were received. When a refund is approved, the method and timing are determined after account-owner verification, and funds are not sent to a different account without additional checks." } },
      { title: { ar: "3. الدفع الإلكتروني", en: "3. Electronic payments" }, body: { ar: "عند تفعيل بوابة دفع إلكترونية، يعتمد تنفيذ الاسترداد ومدته على قواعد البوابة وحالة العملية الأصلية. لا نعتمد على صفحة نجاح في المتصفح وحدها لإثبات الدفع أو الاسترداد.", en: "When an electronic gateway is enabled, refund processing and timing depend on gateway rules and the original transaction status. A browser success page alone is not used as proof of payment or refund." } },
      { title: { ar: "4. المنتجات المادية", en: "4. Physical products" }, body: { ar: "استبدال أو استرجاع منتج مادي يخضع لسياسة المتجر البائع والقانون وحالة المنتج والتسليم. سعرلي وسيط تقني وليس البائع، ويمكن استخدام الدعم للمساعدة في توثيق المشكلة دون أن يحل ذلك محل مسؤولية المتجر.", en: "Replacement or return of a physical product follows the seller's policy, applicable law, product condition, and delivery status. Saarly is a technical intermediary, not the seller; support may help document the issue but does not replace the store's responsibility." } },
      { title: { ar: "5. تقديم الطلب", en: "5. Submitting a request" }, body: { ar: "أرسل رقم العملية أو طلب الدفع وسبب الاسترداد والمستندات الداعمة عبر نموذج الدعم من البريد المرتبط بالحساب. سنبلغك بالحالة عبر البريد المسجل.", en: "Send the transaction or payment-request number, refund reason, and supporting documents through the support form using the email linked to the account. Status updates are sent to the registered email." } },
    ],
  },
  deleteAccount: {
    title: { ar: "حذف الحساب", en: "Delete Account" },
    updated: { ar: "آخر تحديث: يوليو 2026", en: "Last updated: July 2026" },
    legalReview: true,
    intro: { ar: "يمكنك طلب حذف حسابك من داخل التطبيق أو من النموذج في هذه الصفحة. نتحقق من ملكية الحساب قبل التنفيذ.", en: "You can request account deletion from the app or the form on this page. Account ownership is verified before processing." },
    sections: [
      { title: { ar: "1. ما الذي يُحذف", en: "1. What is deleted" }, body: { ar: "يتم حذف أو فصل بيانات الدخول والملف الشخصي والبيانات الاختيارية التي لا يلزم الاحتفاظ بها، وإلغاء الأجهزة والجلسات المرتبطة بالحساب وفق إجراءات النظام.", en: "Login and profile data and optional data that does not need to be retained are deleted or detached, and linked devices and sessions are revoked according to system procedures." } },
      { title: { ar: "2. ما الذي قد يُجهّل", en: "2. What may be anonymized" }, body: { ar: "قد تُجهّل الرسائل والتقييمات والسجلات التشغيلية اللازمة للحفاظ على سلامة الطلبات والتقارير، بحيث لا تبقى مرتبطة مباشرة بهوية المستخدم.", en: "Messages, reviews, and operational records needed to preserve request and report integrity may be anonymized so they are no longer directly linked to the user's identity." } },
      { title: { ar: "3. ما الذي قد يُحتفظ به", en: "3. What may be retained" }, body: { ar: "قد نحتفظ بسجلات محدودة مطلوبة للالتزامات القانونية أو المالية أو مكافحة الاحتيال أو تسوية نزاع، مثل سجلات الدفع والفواتير وسجل قرارات الحساب، للمدة التي يفرضها القانون أو الحاجة المشروعة.", en: "Limited records may be retained for legal or financial obligations, fraud prevention, or dispute resolution, such as payment, invoice, and account-decision records, for the period required by law or a legitimate need." } },
      { title: { ar: "4. طريقة الطلب والتأكيد", en: "4. Request and confirmation" }, body: { ar: "أرسل الطلب من البريد المرتبط بالحساب واكتب بوضوح أنك تطلب حذف الحساب. قد نطلب خطوة تحقق إضافية، ثم نرسل تأكيدًا عند قبول الطلب أو توضيحًا إذا تعذر التنفيذ فورًا.", en: "Submit the request from the email linked to the account and clearly state that you request account deletion. Additional verification may be required, followed by confirmation or an explanation if immediate completion is not possible." } },
    ],
  },
};
