"use client";

import Link from "next/link";
import { useState, type FormEvent } from "react";
import { Icon } from "@/components/icons";
import { buyerPost } from "@/components/buyer/portal-client";
import { Notice, PortalPanel } from "@/components/merchant/portal-ui";
import { row, rows, text } from "@/components/merchant/portal-utils";
import type { BuyerSectionProps } from "@/components/buyer/section-props";
import { useSitePreferences } from "@/components/site-preferences";

export function BuyerSettingsSection({ payload, locale, refresh, notify }: BuyerSectionProps) {
  const { setLocale, setTheme } = useSitePreferences();
  const profile = payload.account.profile;
  const savedLocation = row(payload.data.location);
  const options = rows(payload.data.locationOptions).filter((item) => item.is_country_marker !== true);
  const [fullName, setFullName] = useState(text(profile.full_name));
  const [mobile, setMobile] = useState(text(profile.mobile));
  const [language, setLanguage] = useState(text(profile.preferred_language, locale) === "en" ? "en" : "ar");
  const [theme, setLocalTheme] = useState(text(profile.theme, "light") === "dark" ? "dark" : "light");
  const [cityId, setCityId] = useState(text(savedLocation.city_id));
  const [latitude, setLatitude] = useState(text(savedLocation.latitude));
  const [longitude, setLongitude] = useState(text(savedLocation.longitude));
  const [saving, setSaving] = useState("");

  async function saveProfile(event: FormEvent) { event.preventDefault(); setSaving("profile"); try { await buyerPost("save_profile", { fullName, mobile }); notify(locale === "ar" ? "تم حفظ بيانات الحساب." : "Account details saved.", "success"); await refresh(); } catch (error) { notify(error instanceof Error ? error.message : "profile_save_failed", "error"); } finally { setSaving(""); } }
  async function savePreferences(event: FormEvent) { event.preventDefault(); setSaving("preferences"); try { await buyerPost("save_preferences", { language, theme }); setLocale(language); setTheme(theme); notify(locale === "ar" ? "تم حفظ اللغة والمظهر." : "Language and appearance saved.", "success"); await refresh(); } catch (error) { notify(error instanceof Error ? error.message : "preferences_save_failed", "error"); } finally { setSaving(""); } }
  async function saveLocation(event: FormEvent) { event.preventDefault(); setSaving("location"); try { await buyerPost("save_location", { cityId, latitude, longitude }); notify(locale === "ar" ? "تم حفظ الموقع والعملة." : "Location and currency saved.", "success"); await refresh(); } catch (error) { notify(error instanceof Error ? error.message : "location_save_failed", "error"); } finally { setSaving(""); } }
  function locate() { if (!navigator.geolocation) return; navigator.geolocation.getCurrentPosition((position) => { setLatitude(String(position.coords.latitude)); setLongitude(String(position.coords.longitude)); }, () => notify(locale === "ar" ? "تعذر الوصول لموقعك." : "Could not access your location.", "error"), { enableHighAccuracy: true, timeout: 12000 }); }

  return <div className="portal-section-stack">
    <div className="portal-two-columns"><PortalPanel title={locale === "ar" ? "بيانات الحساب" : "Account details"}><form className="portal-form" onSubmit={saveProfile}><label>{locale === "ar" ? "الاسم بالكامل" : "Full name"}<input required minLength={2} value={fullName} onChange={(event) => setFullName(event.target.value)}/></label><label>{locale === "ar" ? "رقم الهاتف" : "Phone number"}<input required minLength={7} inputMode="tel" value={mobile} onChange={(event) => setMobile(event.target.value)}/></label><label>{locale === "ar" ? "البريد" : "Email"}<input value={payload.account.email} readOnly/></label><button className="button primary" disabled={saving === "profile"}>{locale === "ar" ? "حفظ البيانات" : "Save details"}</button></form></PortalPanel><PortalPanel title={locale === "ar" ? "موقعك والعملة" : "Location and currency"}><form className="portal-form" onSubmit={saveLocation}><label>{locale === "ar" ? "الدولة والمحافظة والمدينة" : "Country, governorate, and city"}<select required value={cityId} onChange={(event) => setCityId(event.target.value)}><option value="">{locale === "ar" ? "اختر الموقع" : "Choose location"}</option>{options.map((item) => <option key={text(item.id)} value={text(item.id)}>{locale === "ar" ? `${text(item.country_ar)} - ${text(item.governorate_ar)} - ${text(item.name_ar)}` : `${text(item.country_en)} - ${text(item.governorate_en)} - ${text(item.name_en)}`}</option>)}</select></label><div className="coordinate-inline"><input inputMode="decimal" placeholder={locale === "ar" ? "خط العرض" : "Latitude"} value={latitude} onChange={(event) => setLatitude(event.target.value)}/><input inputMode="decimal" placeholder={locale === "ar" ? "خط الطول" : "Longitude"} value={longitude} onChange={(event) => setLongitude(event.target.value)}/></div><button className="button secondary" type="button" onClick={locate}><Icon name="location"/>{locale === "ar" ? "استخدام موقعي" : "Use my location"}</button><button className="button primary" disabled={saving === "location"}>{locale === "ar" ? "حفظ الموقع" : "Save location"}</button></form></PortalPanel></div>
    <PortalPanel title={locale === "ar" ? "اللغة والمظهر" : "Language and appearance"} subtitle={locale === "ar" ? "التفضيلات تتزامن مع حسابك في التطبيق." : "Preferences stay synced with your app account."}><form className="portal-form" onSubmit={savePreferences}><div className="setting-options"><button type="button" className={language === "ar" ? "selected" : ""} onClick={() => setLanguage("ar")}><Icon name="globe"/><strong>العربية</strong></button><button type="button" className={language === "en" ? "selected" : ""} onClick={() => setLanguage("en")}><Icon name="globe"/><strong>English</strong></button></div><div className="setting-options"><button type="button" className={theme === "light" ? "selected" : ""} onClick={() => setLocalTheme("light")}><Icon name="sun"/><strong>{locale === "ar" ? "فاتح" : "Light"}</strong></button><button type="button" className={theme === "dark" ? "selected" : ""} onClick={() => setLocalTheme("dark")}><Icon name="moon"/><strong>{locale === "ar" ? "داكن" : "Dark"}</strong></button></div><button className="button primary" disabled={saving === "preferences"}>{locale === "ar" ? "حفظ التفضيلات" : "Save preferences"}</button></form></PortalPanel>
    <div className="portal-two-columns"><PortalPanel title={locale === "ar" ? "روابط المساعدة" : "Help links"}><div className="settings-links"><Link href="/buyer/support"><Icon name="quote"/><span><strong>{locale === "ar" ? "الدعم والمساعدة" : "Support"}</strong><small>{locale === "ar" ? "محادثة متزامنة مع التطبيق." : "A chat synced with the app."}</small></span><Icon name="chevron"/></Link><Link href="/privacy"><Icon name="shield"/><span><strong>{locale === "ar" ? "سياسة الخصوصية" : "Privacy policy"}</strong></span><Icon name="chevron"/></Link><Link href="/terms"><Icon name="receipt"/><span><strong>{locale === "ar" ? "شروط الاستخدام" : "Terms of use"}</strong></span><Icon name="chevron"/></Link></div></PortalPanel><PortalPanel title={locale === "ar" ? "إجراءات الحساب" : "Account actions"}><Notice tone="warning">{locale === "ar" ? "حذف الحساب يخضع لمراجعة السجلات القانونية والطلبات المرتبطة بالحساب." : "Account deletion is reviewed against legal and order records."}</Notice><Link className="button danger-button" href="/delete-account"><Icon name="trash"/>{locale === "ar" ? "طلب حذف الحساب" : "Request account deletion"}</Link></PortalPanel></div>
  </div>;
}
