"use client";
import { MetricCard, PortalPanel, EmptyState } from "@/components/merchant/portal-ui";
import { dateLabel,money,numberValue,row,rows,text } from "@/components/merchant/portal-utils";
import type { SectionProps } from "@/components/merchant/section-props";
export function ReportsSection({payload,locale}:SectionProps){const d=payload.data,s=row(d.summary),g=row(d.growth),branches=rows(d.branches),reviews=rows(d.reviews),currency=text(d.currencyCode,payload.account.currencyCode||"EGP");return <div className="portal-section-stack">
<div className="metrics-grid"><MetricCard icon="money" label={locale==="ar"?"إجمالي المبيعات":"Total sales"} value={money(s.total_sales,currency,locale)}/><MetricCard icon="receipt" label={locale==="ar"?"الطلبات المؤكدة":"Confirmed orders"} value={numberValue(s.confirmed_orders_count)}/><MetricCard icon="check" label={locale==="ar"?"متوسط التقييم":"Average rating"} value={numberValue(s.average_rating).toFixed(1)}/><MetricCard icon="card" label={locale==="ar"?"الرصيد المستحق":"Balance due"} value={money(s.balance_due,currency,locale)}/></div>
<PortalPanel title={locale==="ar"?"النمو والأداء":"Growth and performance"} subtitle={locale==="ar"?"الأرقام محسوبة من بيانات الطلبات والتقييمات الفعلية.":"Metrics are calculated from actual orders and reviews."}><div className="detail-list"><div><span>{locale==="ar"?"مبيعات الفترة":"Period sales"}</span><strong>{money(g.total_sales||s.total_sales,currency,locale)}</strong></div><div><span>{locale==="ar"?"عدد التقييمات":"Reviews"}</span><strong>{numberValue(s.reviews_count)}</strong></div><div><span>{locale==="ar"?"نهاية الفترة الحالية":"Current period end"}</span><strong>{dateLabel(s.current_period_end,locale)}</strong></div><div><span>{locale==="ar"?"الخطة":"Plan"}</span><strong>{text(locale==="ar"?s.plan_name_ar:s.plan_name_en,locale==="ar"?"غير محددة":"Not set")}</strong></div></div></PortalPanel>
<PortalPanel title={locale==="ar"?"أداء الفروع":"Branch performance"}>{branches.length?<div className="portal-table-wrap"><table className="portal-table"><thead><tr><th>{locale==="ar"?"الفرع":"Branch"}</th><th>{locale==="ar"?"الطلبات":"Orders"}</th><th>{locale==="ar"?"المؤكدة":"Confirmed"}</th><th>{locale==="ar"?"المبيعات":"Sales"}</th><th>{locale==="ar"?"آخر بيع":"Last sale"}</th></tr></thead><tbody>{branches.map(b=><tr key={text(b.branch_id)}><td>{text(b.branch_name)}</td><td>{numberValue(b.orders_count)}</td><td>{numberValue(b.confirmed_orders_count)}</td><td>{money(b.total_sales,currency,locale)}</td><td>{dateLabel(b.last_sale_at,locale)}</td></tr>)}</tbody></table></div>:<EmptyState title={locale==="ar"?"لا توجد مبيعات للفروع":"No branch sales yet"} body={locale==="ar"?"تظهر البيانات بعد أول طلب مؤكد.":"Data appears after the first confirmed order."}/>}</PortalPanel>
<PortalPanel title={locale==="ar"?"أحدث التقييمات":"Latest reviews"}>{reviews.length?<div className="review-grid">{reviews.slice(0,20).map(r=><article className="review-card" key={text(r.id)}><strong>{"★".repeat(Math.max(1,Math.min(5,numberValue(r.stars))))}</strong><p>{text(r.comment,locale==="ar"?"بدون تعليق":"No comment")}</p><small>{dateLabel(r.created_at,locale)}</small></article>)}</div>:<EmptyState title={locale==="ar"?"لا توجد تقييمات":"No reviews yet"} body={locale==="ar"?"تظهر تقييمات العملاء هنا بعد اكتمال الطلبات.":"Buyer reviews appear here after completed orders."}/>}</PortalPanel></div>}
